spring:
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.19:5432/springrestspecialist
    username: postgres
    password: root
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      idle-timeout: 10000

  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
